services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        source: node_modules_cached
        target: /app/node_modules
    depends_on:
      - backend
      - mongo_db
    networks:
      - frontend_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./backend
        target: /app
    depends_on:
      - mongo_db
    networks:
      - frontend_network
      - backend_network
    restart: unless-stopped

  mongo_db:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
    networks:
      - backend_network
    restart: unless-stopped

networks:
  frontend_network:
  backend_network:

volumes:
  node_modules_cached:
  mongo_data:
